name: Go
on: [push]
jobs:

  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.22.x' ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: test
      run: |
        make vet
        make test
        make fuzz
